"""
Newsletter Agent for generating the final markdown newsletter.

This agent is responsible for:
- Combining all processed content
- Organizing content into sections
- Generating clean markdown output
- Formatting the newsletter for readability
"""

import logging
from typing import List, Dict, Any
from datetime import datetime

from config.settings import DATE_FORMAT

logger = logging.getLogger(__name__)


class NewsletterAgent:
    """Agent for generating the final AI newsletter."""

    def __init__(self):
        """Initialize the NewsletterAgent."""
        self.date = datetime.now().strftime(DATE_FORMAT)

    def generate(
        self,
        articles_bullets: List[str],
        papers_bullets: List[str],
        posts_bullets: List[str],
        themes: List[str],
    ) -> str:
        """
        Generate the complete newsletter in markdown format.

        Args:
            articles_bullets: Bullet points for news articles
            papers_bullets: Bullet points for research papers
            posts_bullets: Bullet points for newsletter posts
            themes: List of emerging themes

        Returns:
            Complete newsletter as markdown string
        """
        logger.info("Generating newsletter")

        newsletter = self._create_header()

        if articles_bullets:
            newsletter += self._create_section("Major AI News", articles_bullets)

        if papers_bullets:
            newsletter += self._create_section("Important Research Papers", papers_bullets)

        if posts_bullets:
            newsletter += self._create_section(
                "Insights from AI Newsletters", posts_bullets
            )

        if themes:
            newsletter += self._create_themes_section(themes)

        newsletter += self._create_footer()

        return newsletter

    def _create_header(self) -> str:
        """
        Create the newsletter header.

        Returns:
            Header markdown string
        """
        header = f"""# Daily AI Newsletter

**Date:** {self.date}

---

"""
        return header

    def _create_section(self, title: str, bullets: List[str]) -> str:
        """
        Create a newsletter section with bullet points.

        Args:
            title: Section title
            bullets: List of bullet point strings

        Returns:
            Section markdown string
        """
        section = f"## {title}\n\n"

        for bullet in bullets:
            section += f"* {bullet}\n\n"

        section += "---\n\n"

        return section

    def _create_themes_section(self, themes: List[str]) -> str:
        """
        Create the emerging themes section.

        Args:
            themes: List of themes

        Returns:
            Themes section markdown string
        """
        section = "## Emerging Themes\n\n"

        section += "Key themes appearing across today's content:\n\n"

        for theme in themes:
            section += f"* **{theme}**\n"

        section += "\n---\n\n"

        return section

    def _create_footer(self) -> str:
        """
        Create the newsletter footer.

        Returns:
            Footer markdown string
        """
        footer = """## How to Subscribe

This newsletter is generated daily at 7:00 AM UTC.

Subscribe to the individual sources for more information:
* [Import AI](https://importai.substack.com)
* [Latent Space](https://latentspace.substack.com)
* [The Sequence](https://thesequence.substack.com)
* [Ben's Bites](https://bensbites.substack.com)

---

*Generated by Daily AI Newsletter Generator*
"""
        return footer

    def save_newsletter(self, content: str, output_path: str) -> bool:
        """
        Save the newsletter to a markdown file.

        Args:
            content: Newsletter markdown content
            output_path: Path to save the file

        Returns:
            True if successful, False otherwise
        """
        try:
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(content)
            logger.info(f"Newsletter saved to {output_path}")
            return True
        except Exception as e:
            logger.error(f"Failed to save newsletter: {e}")
            return False
